@url = http://localhost:3000 

GET {{url}}
###  Send Get Request to autores
GET {{url}}/api/autores
###  Send Post Request to autores
POST {{url}}/api/autores/create
Content-Type: application/json

{
    "nombre": "Jorge Luis Borges",
    "imagen": "https://ejemplo.com/borges.jpg",
    "email": "jorge@ejemplo.com"
}

###  Send Delete Request to autores
DELETE {{url}}/api/autores/delete?id=3

### Send Get Request to posts
GET {{url}}/api/posts
### Send Post Request to posts
POST {{url}}/api/posts/create
Content-Type: application/json

{
    "titulo": "El Laberinto Infinito",
    "descripcion": "Cuento filosófico de Jorge Luis Borges.",
    "fecha_creacion": "1970-08-01",
    "categoria": "Filosofía",
    "autores_id": 7
}
###  Send Delete Request to autores
DELETE {{url}}/api/posts/delete?id=3

###  Send Put Request to post
PATCH {{url}}/api/posts/update
Content-Type: application/json

{
    "titulo": "El Laberinto Infinito",
    "descripcion": "Cuento filosófico sobre la complejidad de la realidad y el misterio de la identidad humana de Jorge Luis Borges.",
    "fecha_creacion": "1970-08-01",
    "categoria": "Filosofía",
    "autores_id": 7
}
###  Send Put Request to autores
PUT {{url}}/api/autores/update
Content-Type: application/json
('Jane Austen', 'jane@ejemplo.com', 'https://ejemplo.com/austen.jpg');
{
    "id": 7,
    "nombre": "Jane Austen",
    "imagen": "https://ejemplo.com/austen.jpg",
    "email": "jane@ejemplo.com"
}

### Get posts from author id
GET {{url}}/api/posts/getPostFromAuthorId?id=1

### Get posts from author name or email equal
GET {{url}}/api/posts/getPostFromAuthorNameOrEmailEqual?filter=William Shakespeare

### Get posts from author name or email like
GET {{url}}/api/posts/getPostFromAuthorNameOrEmailLike?filter=Shakespeare
