@url = http://localhost:3000 

GET {{url}}
###  Send Get Request to autores
GET {{url}}/api/autores
###  Send Post Request to autores
POST {{url}}/api/autores/create
Content-Type: application/json

{
    "nombre": "William Shakespeare",
    "imagen": "url de imagen",
    "email": "shakespeare@gmail.com"
}
###  Send Delete Request to autores
DELETE {{url}}/api/autores/delete?id=2

### Send Get Request to posts
GET {{url}}/api/posts
### Send Post Request to posts
POST {{url}}/api/posts/create
Content-Type: application/json

{
    "titulo": "Titulo post 2",
    "descripcion": "Contenido del post ",
    "fecha_creacion": "2024-10-08 09:19:00",
    "categoria": "Categoría del post 2",
    "autores_id": 1
}
###  Send Delete Request to autores
DELETE {{url}}/api/posts/delete?id=2
